server:
  error:
    include-message: always
    include-binding-errors: always
jwt:
  secret:
    key: 217A25432A46294A404E635266556A586E3272357538782F413F4428472B4B62
#    "217A25432A46294A404E635266556A586E3272357538782F413F4428472B4B62"
  #    ENC(dQOXQVNUAXJch5k9hIm95eeyQUAggYvMhiwqIvZ1PMh2)
spring:
  datasource:
    password: ENC(EqXk9lxpiVtcHdVJlbyi+9Ks2VnXKM3N)
    url: jdbc:postgresql://localhost:5432/register
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: jordanvoss98@gmail.com
    password: moxhbbzqqymmjcow

    #    ENC(CncD/LvJqME/V90L2GI8BEWgRFGksMQss+76iW0LN30=)


    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        debug: true